sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

addons:
  chrome: stable

node_js:
  - "8"

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
- ng test